// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:1042379936536:web:889a32e27449435d3c846d',
    messagingSenderId: '1042379936536',
    projectId: 'club-fitness-c7cdf',
    authDomain: 'club-fitness-c7cdf.firebaseapp.com',
    storageBucket: 'club-fitness-c7cdf.firebasestorage.app',
    measurementId: 'G-K0Y3GY297M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:1042379936536:android:fe8dff9e1ba89b743c846d',
    messagingSenderId: '1042379936536',
    projectId: 'club-fitness-c7cdf',
    storageBucket: 'club-fitness-c7cdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:1042379936536:ios:ed3df9ffa7ee6c9a3c846d',
    messagingSenderId: '1042379936536',
    projectId: 'club-fitness-c7cdf',
    storageBucket: 'club-fitness-c7cdf.firebasestorage.app',
    iosBundleId: 'com.example.clubFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:1042379936536:ios:ed3df9ffa7ee6c9a3c846d',
    messagingSenderId: '1042379936536',
    projectId: 'club-fitness-c7cdf',
    storageBucket: 'club-fitness-c7cdf.firebasestorage.app',
    iosBundleId: 'com.example.clubFitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:1042379936536:web:417598144389be893c846d',
    messagingSenderId: '1042379936536',
    projectId: 'club-fitness-c7cdf',
    authDomain: 'club-fitness-c7cdf.firebaseapp.com',
    storageBucket: 'club-fitness-c7cdf.firebasestorage.app',
    measurementId: 'G-3MVH7WENJ1',
  );
}
